### ISSUE TITLE
error in main.py

### ISSUE THREAD

**Issue by ComingPeopleHW** [PanPapag/Image-to-Image-Translation#1]
hello, I think is there a error in main.py?
the code is :`if device == 'cuda':`
because the type of 'device' in your code is <class 'torch.device'>, so `if device == 'cuda'` alaways retun false.

my enviroment:
pytorch 1.60

**Comment by PanPapag** [comment]
@ComingPeopleHW  Thanks for the issue! You are right, the correct one is `if device.type == 'cuda'`. I've just fixed it!

**Comment by PanPapag** [comment]
@ComingPeopleHW  Thanks for the issue! You are right, the correct one is `if device.type == 'cuda'`. I've just fixed it!
